agent:
  model:
    name: openai/mistral-small-4-119b-nvfp4
    api_key: $VLLM_API_KEY
    per_instance_cost_limit: 0
    total_cost_limit: 0
    per_instance_call_limit: 100
    temperature: 0
    top_p: 1
    max_input_tokens: 0
    max_output_tokens: 65536
    completion_kwargs:
      max_tokens: 65536
      seed: 1234
      reasoning_effort: none
